package ch.noseryoung.warenkorb.products;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

public class Cart {
    @Id
    @GeneratedValue
    int id;       //Autogenerated id
    @Column(name = "product")
    String product;         //Name of the Product.
    @Column(name = "brand")
    String brand;           //Name of the Brand.

     public int getId(){
        return id;
    }
    public String getProduct(){
         return product;
    }
    public String getBrand(){
         return brand;
    }
}
