package ch.noseryoung.warenkorb.cart;

import ch.qos.logback.core.testUtil.StringListAppender;
import jakarta.persistence.*;

import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "cart")
public class Cart {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;       //Autogenerated id
    @Column (name = "product")
    private String product;
    @Column(name = "quantity")
    private int quantity;           //amount of certain product.


    public UUID getId() {
        return id;
    }


    public void setId(UUID id) {
        this.id = id;
    }

    public int getQuantity() {
        return quantity;
    }

    public void getQuantity(int quantity) {
        this.quantity = quantity;
    }
}