package ch.noseryoung.warenkorb.cart;

import jakarta.persistence.*;

import java.util.UUID;

@Entity
@Table(name = "cart")
public class Cart {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID cartId;       //Autogenerated id
    @Column(name = "product")
    private String product;
    @Column(name = "quantity")
    private int quantity;           //amount of certain product.


    public UUID getId() {
        return cartId;
    }


    public void setId(UUID cartId) {
        this.cartId = cartId;
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public int getQuantity() {
        return quantity;
    }

    public void getQuantity(int quantity) {
        this.quantity = quantity;
    }
}